# USB capacitive touch panels usually present as HID touchscreens.
Section "InputClass"
	Identifier "libinput touchscreen catchall"
	MatchIsTouchscreen "on"
	MatchDevicePath "/dev/input/event*"
	Driver "libinput"
EndSection
